# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-k8s"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "controller" do |ctl|
    ctl.vm.hostname = "kubernetes-controller"
    ctl.vm.network :private_network, ip: "10.8.8.10"
    ctl.vm.provision :shell, path: "bootstrap-controller.sh"
    ctl.vm.provision :shell, path: "k8s-common.sh", privileged: false
  end

  config.vm.define "node1" do |n1|
    n1.vm.hostname = "kubernetes-worker-1"
    n1.vm.network :private_network, ip: "10.8.8.11"
    n1.vm.provision :shell, path: "bootstrap-node.sh", args: "1"
  end

  config.vm.define "node2" do |n2|
    n2.vm.hostname = "kubernetes-worker-2"
    n2.vm.network :private_network, ip: "10.8.8.12"
    n2.vm.provision :shell, path: "bootstrap-node.sh", args: "2"
  end
end
